### ISSUE TITLE
Redirect link not being created?

### ISSUE THREAD

**Issue by philipobrien** [OPENi-ict/openi-js-lib#5]
I have been looking at the demo code and notice that the [redirect function](https://github.com/OPENi-ict/openi-js-lib/blob/master/openi-js-lib/openi_js_lib.js#L42) doesn't get passed any parameters. Instead the `openi_js_lib.js` file sets the parameters as empty strings, so the redirect link that gets created is http://demo2.openi-ict.eu/auth/account?api_key=&secret=&redirectURL=

Am I missing something?

**Comment by pmatzavin** [comment]
Hi P*hilipobrien <https://github.com/philipobrien>,*

The parameters are declared as empty strings.
The initOpeni(...) function defined in the openi_js_lib.js,  takes as
arguments the values that are used to initialize these parameters.
So, when the initOpeni(...) function is being executed, it sets the
appropriate values to the parameters.

-->The redirect function should be called after the initOpeni(...) has
finished its execution.
 (which means that the parameters would be correctly initialized with the
values that were given as arguments to the initOpeni() function).

I will look into it in more detail to validate the functionality, and i
will provide a more detailed answer (along with any code fixes if need)

Note that the http://www.openi-ict.eu/ and the http://demo2.openi-ict.eu/
servers were down today (they are still down the last time i checked, a few
minutes ago)
which may cause some problems (because the initOpeni function will not be
able finish its execution successfully).

Regards,
Panos Matzavinos

2015-03-23 17:36 GMT+02:00 philipobrien <notifications@github.com>:

**Comment by philipobrien** [comment]
Hi Panos, thanks for the detailed reply. That explains things
